version: '3.7'

services:
    database:
        image: postgres
        container_name: recomendation-app-db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=adminPass
            - POSTGRES_DB=ebdb
        volumes:
            - pgdata:/data/postgres
        expose: 
            - "5432"

    # app:
    #     build: .
    #     container_name: recomendation-api
    #     ports:
    #         - 3333:3333
    #         - 9229:9229
    #     volumes:
    #         - .:/usr/app
    #     depends_on:
    #         - database
    #     environment:
    #         DB_HOST: database
    #         DB_PORT: 5432
    #         DB_USER: admin
    #         DB_PASSWORD: adminPass
    #         DB_NAME: ebdb
    #     links:
    #         - database


volumes:
    pgdata:
        driver: local
